### ISSUE TITLE
RM_BSPCut.png/RM_BSPCutS.png

### ISSUE THREAD

**Issue by metallicafan212** [metallicafan212/M212-Editor-Issue-Tracker#10]
Show BSP cuts

**Comment by OmegaRC59** [comment]
![RM_BSPCutS](https://user-images.githubusercontent.com/66154598/88257221-1a6e5d80-cc72-11ea-94ed-4b32ab8356be.png)
![RM_BSPCut](https://user-images.githubusercontent.com/66154598/88257223-1b06f400-cc72-11ea-8537-4410adf2e687.png)
