### ISSUE TITLE
RM_DynLit.png/RM_DynLitS.png

### ISSUE THREAD

**Issue by metallicafan212** [metallicafan212/M212-Editor-Issue-Tracker#11]
Dynamic light render mode

**Comment by OmegaRC59** [comment]
![RM_DynLitS](https://user-images.githubusercontent.com/66154598/88255866-6f0fd980-cc6e-11ea-8070-f6fedd165bc6.png)
![RM_DynLit](https://user-images.githubusercontent.com/66154598/88255869-6fa87000-cc6e-11ea-9516-b36eac3fa0d2.png)
