### ISSUE TITLE
[BUG] Removing custom actor from a package crashes the editor

### ISSUE THREAD

**Issue by AdamJD01** [metallicafan212/M212-Editor-Issue-Tracker#113]
Trying to load a map that has had a custom actor removed from a package crashes the editor with no error or nothing in the log but gives this error in game when trying to play the map. 

<img width="310" alt="Untitled" src="https://user-images.githubusercontent.com/54454429/88614921-b3451480-d088-11ea-9dd5-8b29e5961745.png">

This didn't happen before, the map would load fine after removing a custom actor from a package in the past.

**Comment by metallicafan212** [comment]
I made some changes to the way I handle missing content (as the game does not have handlers for missing content by default) but I might have screwed it up a bit.

Mind posting the level so I can test?

**Comment by AdamJD01** [comment]
Sent it in Discord

**Comment by metallicafan212** [comment]
Fixed
