### ISSUE TITLE
[BUG] Hovering over items in the bottom toolbar makes them constantly flicker on and off

### ISSUE THREAD

**Issue by AdamJD01** [metallicafan212/M212-Editor-Issue-Tracker#114]
When hovering the mouse over items in the bottom toolbar the items constantly flicker on and off (disappear and reappear).

**Comment by metallicafan212** [comment]
Yeah, I knew about that. The flickering tools are windows controls and I
can't control when they print.

Eventually I might just get fed up and make my own combo boxes and edit
controls.

**Comment by metallicafan212** [comment]
Marking this as wontfix for right now as the only solution is to make a custom combo box implementation.

**Comment by AdamJD01** [comment]
Closing because this is now a duplicate
