### ISSUE TITLE
Viewport Context Menu Additions

### ISSUE THREAD

**Issue by OmegaRC59** [metallicafan212/M212-Editor-Issue-Tracker#115]
Will come up with more as time goes on:

- ~~Replace Add Light with a full list of all light types, similar to the add mover button's right click function~~

- ~~Add a navigation point dropdown similarly to that~~

- ~~Triggers dropdown~~

- ~~Also add a ~~BlockActor~~ Keypoint types dropdown (So Blockall, Player, Monsters, etc)~~

- Other actors to add singularly to the list: 
- ~~Ambient Sound (Sets the ambient sound to also have the current sound that's selected, similarly to how UE2 spawns static meshes)~~
- Cutscene
- Cutmark 

We could have a dropdown called like "Level Design" or something, and add actors to it that are typical for HP2 level design like savepoints and stuff. Could have the objects such as Triggers in there.

**Comment by metallicafan212** [comment]
Added dynamically loaded light dropdown

**Comment by metallicafan212** [comment]
Added dynamically loaded navigation point dropdown

**Comment by metallicafan212** [comment]
Added dynamically loaded trigger dropdown

**Comment by metallicafan212** [comment]
Added keypoint dynamically loaded dropdown

**Comment by metallicafan212** [comment]
Added automatic ambient sound

**Comment by metallicafan212** [comment]
Added the other actors.

**Comment by metallicafan212** [comment]
Closing for now until there's more we want to add
