### ISSUE TITLE
RM_Front.png/RM_FrontS.png

### ISSUE THREAD

**Issue by metallicafan212** [metallicafan212/M212-Editor-Issue-Tracker#12]
Ortho Front icon

**Comment by OmegaRC59** [comment]
![RM_FrontS](https://user-images.githubusercontent.com/66154598/88242428-ff83f500-cc41-11ea-8cc8-9b0bfcce961a.png)
![RM_Front](https://user-images.githubusercontent.com/66154598/88242429-001c8b80-cc42-11ea-8416-92ab44a909d8.png)
