### ISSUE TITLE
Support Looping Textures like UE2

### ISSUE THREAD

**Issue by MaxG-cmd** [metallicafan212/M212-Editor-Issue-Tracker#122]
Currently it seems that certain UVs just break in this engine, and I don't really know why.

![image](https://user-images.githubusercontent.com/56568996/90321203-25cd4580-df0d-11ea-969c-2cf64869898c.png)

![image](https://user-images.githubusercontent.com/56568996/90321214-3f6e8d00-df0d-11ea-8f32-05c0dadbb97a.png)

**Comment by OmegaRC59** [comment]
I don't think oob UV coordinates are supported for doing looping textures

**Comment by metallicafan212** [comment]
I cannot fix this, as UV coordinates in UE1 are stored as bytes, so I will have to make a new mesh type to support full floating point UV,

**Comment by metallicafan212** [comment]
Newest version of the editor only imports using floating point UVs and it works fine so far.
