### ISSUE TITLE
[BUG ?] Some prefabs are invisible in the editor

### ISSUE THREAD

**Issue by AdamJD01** [metallicafan212/M212-Editor-Issue-Tracker#125]
When adding some prefabs they are invisible in the editor when reloading the map but are visible in game.

**Comment by metallicafan212** [comment]
It's the group browser. Delete all the groups in the group browser and that
will solve the problem. Omega mentioned this before; the group browser is
pretty bad and need a full rework, but that will come later.

**Comment by metallicafan212** [comment]
Made the prefab browser set bHiddenEd to false on paste.
