### ISSUE TITLE
[FEATURE] AmbientGlow Color

### ISSUE THREAD

**Issue by MaxG-cmd** [metallicafan212/M212-Editor-Issue-Tracker#127]
Basically, would something like this be possible?

![image](https://user-images.githubusercontent.com/56568996/90807763-95b04700-e2e4-11ea-8120-d58617dcd114.png)
![image](https://user-images.githubusercontent.com/56568996/90807791-9e088200-e2e4-11ea-80ee-5aa7d1edcda7.png)
![image](https://user-images.githubusercontent.com/56568996/90807815-abbe0780-e2e4-11ea-8a55-1a9c105d7206.png)

**Comment by metallicafan212** [comment]
Not without breaking stock support.

**Comment by metallicafan212** [comment]
Added
