### ISSUE TITLE
Group Browser Icon: Show Actors In Group

### ISSUE THREAD

**Issue by metallicafan212** [metallicafan212/M212-Editor-Issue-Tracker#129]
TB_GR_Show.png

**Comment by OmegaRC59** [comment]
Closing because we're using the checkboxes

**Comment by metallicafan212** [comment]
Reopening because Omega is a dunce and doesn't realize this is a separate button for doing all selected groups AT ONCE.

**Comment by OmegaRC59** [comment]
![TB_GR_Show](https://user-images.githubusercontent.com/66154598/96056970-befcd780-0e3c-11eb-9814-c5a461c0feb9.png)
