### ISSUE TITLE
RM_LghtOnly.png/RM_LghtOnlyS.png

### ISSUE THREAD

**Issue by metallicafan212** [metallicafan212/M212-Editor-Issue-Tracker#13]
Lighting only render mode

**Comment by OmegaRC59** [comment]
![RM_LghtOnly](https://user-images.githubusercontent.com/66154598/88255414-37546200-cc6d-11ea-86bc-097fddcd2891.png)
![RM_LghtOnlyS](https://user-images.githubusercontent.com/66154598/88255415-37ecf880-cc6d-11ea-90c9-50edbe687358.png)
