### ISSUE TITLE
Group Browser Icon: Hide Actors In Group

### ISSUE THREAD

**Issue by metallicafan212** [metallicafan212/M212-Editor-Issue-Tracker#130]
TB_GR_Hide.png

**Comment by OmegaRC59** [comment]
I'm closing because we're using the checkboxes instead

**Comment by metallicafan212** [comment]
Reopening because Omega is a dunce and doesn't realize this is a separate button for doing all selected groups AT ONCE.

**Comment by OmegaRC59** [comment]
poopyhead hehe

**Comment by OmegaRC59** [comment]
![TB_GR_Hide](https://user-images.githubusercontent.com/66154598/96056956-b7d5c980-0e3c-11eb-9ed4-ab283bc6cb17.png)
