### ISSUE TITLE
[BUG] Textured View Being Affected by ScaleGlow

### ISSUE THREAD

**Issue by MaxG-cmd** [metallicafan212/M212-Editor-Issue-Tracker#131]
Meshes with ScaleGlow not equal to 1 will appear brighter/darker in textured view mode.

**Comment by metallicafan212** [comment]
*shut*

**Comment by metallicafan212** [comment]
This is the stock behavior, it's literally programmed to be this way.

Don't really see a reason to make a button for it either, as it's pretty useless.
