### ISSUE TITLE
[BUG] DX9 crash 

### ISSUE THREAD

**Issue by AdamJD01** [metallicafan212/M212-Editor-Issue-Tracker#134]
Got this DX9 error when using the editor. 

<img width="304" alt="Untitled" src="https://user-images.githubusercontent.com/54454429/92278089-5856d680-eeec-11ea-9214-174f647da137.png">

**Comment by OmegaRC59** [comment]
Mind attaching your log too?

**Comment by metallicafan212** [comment]
What were you doing at the time?

**Comment by AdamJD01** [comment]
I no longer have the log.

I was looking around Willow inspecting different actors.

**Comment by metallicafan212** [comment]
This shouldn't happen anymore.
