### ISSUE TITLE
[FEATURE] bEdShouldSnap to make the actor snap to the current grid size

### ISSUE THREAD

**Issue by MaxG-cmd** [metallicafan212/M212-Editor-Issue-Tracker#135]
![image](https://user-images.githubusercontent.com/56568996/92748777-18a84880-f34b-11ea-9cec-57eb0c5025b2.png)

**Comment by metallicafan212** [comment]
Not a bug, bEdShouldSnap only applies to the builder brush per the comments.

**Comment by metallicafan212** [comment]
Also attach more to the issues my man, don't try to play word-soup with the titles.

**Comment by AdamJD01** [comment]
Implemented
