### ISSUE TITLE
Sound Browser: Play on click enabled/disabled

### ISSUE THREAD

**Issue by metallicafan212** [metallicafan212/M212-Editor-Issue-Tracker#136]
Icons for showing the mode is enabled and disabled.

TB_SPlayOC_e.png = enabled
TB_SPlayOC.png     = disabled

**Comment by OmegaRC59** [comment]
![TB_SPlayOC](https://user-images.githubusercontent.com/66154598/96056929-aab8da80-0e3c-11eb-9b82-932d338cb34c.png)
![TB_SPlayOC_e](https://user-images.githubusercontent.com/66154598/96056933-ab517100-0e3c-11eb-88df-2c816bbd422a.png)
