### ISSUE TITLE
[BUG] Reset to Default button incorrect position

### ISSUE THREAD

**Issue by MaxG-cmd** [metallicafan212/M212-Editor-Issue-Tracker#137]
![image](https://user-images.githubusercontent.com/56568996/93226458-f5114380-f738-11ea-84c1-edd50f336cb0.png)
The button moves as you scroll

![image](https://user-images.githubusercontent.com/56568996/93226501-022e3280-f739-11ea-8c06-32e6944c2bb4.png)

**Comment by metallicafan212** [comment]
This is now fixed. They scroll with items now.
