### ISSUE TITLE
[FEATURE] Big Vertices Option

### ISSUE THREAD

**Issue by MaxG-cmd** [metallicafan212/M212-Editor-Issue-Tracker#139]
![image](https://user-images.githubusercontent.com/56568996/93262218-7a145100-f769-11ea-93e6-4e213aa018b2.png)
UE2 has this feature that allows the brush vertices to draw larger

**Comment by metallicafan212** [comment]
Implemented
![image](https://user-images.githubusercontent.com/5996243/95156594-c3920380-074b-11eb-99e9-25a5e5b019bf.png)
