### ISSUE TITLE
RM_Play.png/RM_PlayS.png

### ISSUE THREAD

**Issue by metallicafan212** [metallicafan212/M212-Editor-Issue-Tracker#14]
The play map button

**Comment by OmegaRC59** [comment]
![RM_Play](https://user-images.githubusercontent.com/66154598/88242442-0ad72080-cc42-11ea-9dbf-02adfd48b74f.png)
![RM_PlayS](https://user-images.githubusercontent.com/66154598/88242443-0b6fb700-cc42-11ea-94a6-cdebf5ad20ac.png)
