### ISSUE TITLE
[BUG] Cutscene skipping messes with game audio

### ISSUE THREAD

**Issue by MaxG-cmd** [metallicafan212/M212-Editor-Issue-Tracker#142]
When holding down the cutscene skip button in an unskippable cutscene, the audio for the game stops playing.

For skippable cutscenes, bits of the audio still play as the cutscene is being skipped.

**Comment by OmegaRC59** [comment]
Bruh I swear this got fixed

**Comment by metallicafan212** [comment]
This isn't something I can fix at the moment. The game gives no context to a cutscene skip; it just sends "MUTEAUDIO" to the audio device when cutscene skipping and "UNMUTEAUDIO" when it's done.

**Comment by metallicafan212** [comment]
Fixed it in the UScript decomp
