### ISSUE TITLE
[BUG] Black screen when loading game with -nofrontend (happens now and then)

### ISSUE THREAD

**Issue by AdamJD01** [metallicafan212/M212-Editor-Issue-Tracker#143]
On times the game doesn't fade in and has a black screen when loading with -nofrontend. 

Holding down the left mouse button fades the game in and gets rid of the black screen when this does happen though.

**Comment by metallicafan212** [comment]
What map? Fade in are controlled by cutscript and can't be "fixed" in the traditional sense.

Also make sure to add -GameState=GSTATE000 to have a valid gamestate without the frontend.

**Comment by AdamJD01** [comment]
The startup map

**Comment by metallicafan212** [comment]
This needs more testing

**Comment by metallicafan212** [comment]
This doesn't happen when you don't use -nofrontend, so I think it's a UScript issue, not a C++ issue.
