### ISSUE TITLE
[BUG] Mouse cursor not updating in brush builder

### ISSUE THREAD

**Issue by MaxG-cmd** [metallicafan212/M212-Editor-Issue-Tracker#146]
This causes two issues that I have noticed: One is that your mouse cursor will hide while typing and then not show itself again, and the second is that sometimes the cursor stays as the window resize cursor as opposed to the pointer cursor.

The cursor hiding bug is triggered when your mouse cursor is hovering over the fake buttons in the builder window and you begin typing in the property boxes. Now, when you move your cursor, it will stay hidden until you move it off of the fake buttons.

**Comment by metallicafan212** [comment]
The first one cannot be solved, it's a stupid Windows thing. I have no control over it.

The second has been fixed
