### ISSUE TITLE
RM_Side.png/RM_SideS.png

### ISSUE THREAD

**Issue by metallicafan212** [metallicafan212/M212-Editor-Issue-Tracker#15]
Ortho side icon

**Comment by OmegaRC59** [comment]
![RM_SideS](https://user-images.githubusercontent.com/66154598/88242452-17f40f80-cc42-11ea-9176-37989043a1f0.png)
![RM_Side](https://user-images.githubusercontent.com/66154598/88242454-188ca600-cc42-11ea-9aa0-1b906d0f570b.png)
