### ISSUE TITLE
[BUG] Destroying an actor that is playing a sound in 2D causes that sound to endlessly loop

### ISSUE THREAD

**Issue by MaxG-cmd** [metallicafan212/M212-Editor-Issue-Tracker#154]

**Comment by MaxG-cmd** [comment]
Related(?): The GridMover Flipendo blocks in Ch7Gryffindor endlessly loop their moving sounds. They don't do this in stock.

**Comment by metallicafan212** [comment]
I think this might be fixed?

**Comment by metallicafan212** [comment]
Closing until confirmed still a bug
