### ISSUE TITLE
[BUG] Selecting an actor and clicking "Reset to defaults" corrupts the actor so you cannot delete it from your map

### ISSUE THREAD

**Issue by MaxG-cmd** [metallicafan212/M212-Editor-Issue-Tracker#157]
![image](https://user-images.githubusercontent.com/56568996/120751813-441d2580-c4ce-11eb-93e4-c0bc2731a7b4.png)

**Comment by metallicafan212** [comment]
I fixed the feature rather than removing it.

Set as defaults has been removed.
