### ISSUE TITLE
RM_Textured.png/RM_TexturedS.png

### ISSUE THREAD

**Issue by metallicafan212** [metallicafan212/M212-Editor-Issue-Tracker#16]
Textures only rendering mode

**Comment by OmegaRC59** [comment]
![RM_TexturedS](https://user-images.githubusercontent.com/66154598/88257131-f1e66380-cc71-11ea-95a9-a53eddf45daa.png)
![RM_Textured](https://user-images.githubusercontent.com/66154598/88257132-f27efa00-cc71-11ea-9b33-b5c426cbc956.png)
