### ISSUE TITLE
[FEATURE] Replace bottom bar text with 4 spaces instead of tabs

### ISSUE THREAD

**Issue by MaxG-cmd** [metallicafan212/M212-Editor-Issue-Tracker#166]
Most of the time selecting this text is fine, however sometimes the text cursor will be offset far to the right from your mouse cursor, making selecting text very difficult. It usually happens with longer names/actors.

![image](https://user-images.githubusercontent.com/56568996/120932258-ad618c00-c6ba-11eb-84c0-c0c74a335f44.png)

**Comment by metallicafan212** [comment]
This is due to the fact that the actual edit control is fake, and the real one is hidden under it. I tried to make the text as close as possible, but it handles text slightly differently than D2D. In the future, I will be replacing the tabs with 4 spaces.

**Comment by metallicafan212** [comment]
This one was closed because I already did it
