### ISSUE TITLE
[BUG] Importing a sound and then double clicking on it crashes the editor

### ISSUE THREAD

**Issue by MaxG-cmd** [metallicafan212/M212-Editor-Issue-Tracker#168]
![image](https://user-images.githubusercontent.com/56568996/121109347-fdcb0d80-c7d0-11eb-907a-d1f00f12700e.png)

**Comment by metallicafan212** [comment]
I tried, I cannot reproduce.

**Comment by metallicafan212** [comment]
It works just find, no issues.
