### ISSUE TITLE
RM_TexUse.png/RM_TexUseS.png

### ISSUE THREAD

**Issue by metallicafan212** [metallicafan212/M212-Editor-Issue-Tracker#17]
Texture use rendering mode

**Comment by OmegaRC59** [comment]
![RM_TexUseS](https://user-images.githubusercontent.com/66154598/88257198-117d8c00-cc72-11ea-93c4-a14dededee0a.png)
![RM_TexUse](https://user-images.githubusercontent.com/66154598/88257199-12162280-cc72-11ea-9edf-b32ec6b98a3e.png)
