### ISSUE TITLE
[FEATURE] Filter sounds in the sound browser

### ISSUE THREAD

**Issue by AdamJD01** [metallicafan212/M212-Editor-Issue-Tracker#171]
wav, xa, mp2 etc

**Comment by metallicafan212** [comment]
It'll have to be just a edit box, so you'll have to know the filetype you want.

**Comment by AdamJD01** [comment]
Also be able to filter sounds by lipsync being off or on

**Comment by metallicafan212** [comment]
Implemented
![image](https://user-images.githubusercontent.com/5996243/142351706-1601857f-ec95-4601-ad40-f23fc6f0067c.png)
