### ISSUE TITLE
[FEATURE] Convert music to ogg in the music browser

### ISSUE THREAD

**Issue by AdamJD01** [metallicafan212/M212-Editor-Issue-Tracker#172]
Open, save, import and export don't do anything when clicked on

**Comment by metallicafan212** [comment]
That's because it was copied from the sound browser so that it didn't look off.

Eventually I'll add in a feature that will allow users to convert to OGG right in the editor, but not right now.

**Comment by AdamJD01** [comment]
Closing because @metallicafan212 has now supported all audio formats
