### ISSUE TITLE
[TEXTURE] Porticle

### ISSUE THREAD

**Issue by MaxG-cmd** [metallicafan212/M212-Editor-Issue-Tracker#178]
![Particle](https://user-images.githubusercontent.com/56568996/125851494-90327229-fb69-455f-8831-be49332bdd31.png)
[Particle.zip](https://github.com/metallicafan212/M212-Editor-Issue-Tracker/files/6825993/Particle.zip)

**Comment by metallicafan212** [comment]
Done
