### ISSUE TITLE
[BUG] Orthographic views rotate brushes along the wrong axis

### ISSUE THREAD

**Issue by MaxG-cmd** [metallicafan212/M212-Editor-Issue-Tracker#179]
![image](https://user-images.githubusercontent.com/56568996/126199815-eb5b6164-a6f5-4d18-9191-501879da0da6.png)
![image](https://user-images.githubusercontent.com/56568996/126199828-9eb8d488-a65f-498e-91c9-0371bd7c72b2.png)
The brush should be rotating clockwise, not... I guess sideways or whatever it's doing

**Comment by AdamJD01** [comment]
Fixed
