### ISSUE TITLE
RM_Top.png/RM_TopS.png

### ISSUE THREAD

**Issue by metallicafan212** [metallicafan212/M212-Editor-Issue-Tracker#18]
Ortho top icon

**Comment by OmegaRC59** [comment]
![RM_TopS](https://user-images.githubusercontent.com/66154598/88242477-2b9f7600-cc42-11ea-84bf-81fb509349bd.png)
![RM_Top](https://user-images.githubusercontent.com/66154598/88242478-2b9f7600-cc42-11ea-9b2e-4a92af3a3abf.png)
