### ISSUE TITLE
[BUG] The mesh browser doesn't get repainted sometimes

### ISSUE THREAD

**Issue by AdamJD01** [metallicafan212/M212-Editor-Issue-Tracker#185]
When maximising the mesh browser sometimes the window does not get repainted correctly. 

![image](https://user-images.githubusercontent.com/54454429/134093333-a894a4a7-2132-4969-afc9-11ab5bdc9372.png)

**Comment by metallicafan212** [comment]
This should be fixed now

**Comment by AdamJD01** [comment]
This still happens, I've added it to version 3

**Comment by AdamJD01** [comment]
This has been improved but not fixed yet

**Comment by AdamJD01** [comment]
Added to Version 4

**Comment by AdamJD01** [comment]
Fixed
