### ISSUE TITLE
[FRONTEND] Bookmarks/level select

### ISSUE THREAD

**Issue by AdamJD01** [metallicafan212/M212-Editor-Issue-Tracker#188]
Be able to select a stock level from the front end (HP3 has this and calls it "Bookmarks").
Would probably have to be a debug mode feature to not mess with save game files.
Also be able to select a gamestate for the hub levels?

**Comment by metallicafan212** [comment]
Pushing this back. I need some more time to think about how I want to do it.

Obviously, this needs to be a separate menu (inside the game options).
On that page, there needs to be a dropdown for gamestate, and other URL variables. Maps can be a subpage to give as much room for a list box as possible.

**Comment by AdamJD01** [comment]
Implemented
