### ISSUE TITLE
RM_Wire.png/RM_WireS.png

### ISSUE THREAD

**Issue by metallicafan212** [metallicafan212/M212-Editor-Issue-Tracker#19]
Wireframe rendering mode

**Comment by OmegaRC59** [comment]
![RM_WireS](https://user-images.githubusercontent.com/66154598/88257182-0a567e00-cc72-11ea-883f-641da4a6f07f.png)
![RM_Wire](https://user-images.githubusercontent.com/66154598/88257183-0a567e00-cc72-11ea-957b-4a8301856442.png)
