### ISSUE TITLE
[FRONTEND] Resizable front end

### ISSUE THREAD

**Issue by AdamJD01** [metallicafan212/M212-Editor-Issue-Tracker#195]
Make the front end resizable for different screen resolutions

**Comment by metallicafan212** [comment]
I was trying to do some fancy aspect ratio correction code, but I just don't have the time or the want to make janky code like that.

I'll just add a scale ini variable....

**Comment by metallicafan212** [comment]
Dragging is now disabled on the FE, but there's a global scale config (M212.M212FrontEnd FEScale) that is applied to the opening size and has a config box in the graphics menu
![image](https://user-images.githubusercontent.com/5996243/147154135-5a793bfd-9dd9-4b25-95f4-fce0bfe24eb3.png)
