### ISSUE TITLE
Fix copy/paste bugs

### ISSUE THREAD

**Issue by metallicafan212** [metallicafan212/M212-Editor-Issue-Tracker#2]
Many different bugs exist with copy/paste. Some cause crashes, others are just annoying.

List the different bugs here.

**Comment by AdamJD01** [comment]
An error when deleting an actor that has been copied and pasted.
<img width="309" alt="deletebug" src="https://user-images.githubusercontent.com/54454429/82732783-48cdcc00-9d07-11ea-878b-60851b96dfcf.png">

**Comment by AdamJD01** [comment]
When copying and pasting sometimes the number at end of the actor does not update

eg.
Instead of getting
AdamJDTrigger0
AdamJDTrigger1
AdamJDTrigger2

This happens instead
AdamJDTrigger0
AdamJDTrigger0
AdamJDTrigger0

**Comment by metallicafan212** [comment]
All these errors should be fixed.

By default, the editor will rename existing actors in a level rather than rename the paste, as it can't paste when the name already exists. Other parts of the paste might rely on that name, so it's better to rename the existing actor, as all references are by ptr rather than by name.

The IsValid problems were fixed by fixing T3D exporting.

**Comment by AdamJD01** [comment]
Deleting an actor that has been copied and pasted doesn't crash the editor anymore but this error happened after saving the level and trying to load another level. 

<img width="309" alt="Untitled" src="https://user-images.githubusercontent.com/54454429/87225268-9d92d800-c383-11ea-87c2-f690033676ce.png">

**Comment by AdamJD01** [comment]
This appears to be fixed, tried replicating it a few times and I don't get an error anymore.

**Comment by AdamJD01** [comment]
Had this error again after deleting an actor I copied and pasted when saving the level and closing the editor.
