### ISSUE TITLE
RM_Zone.png/RM_ZoneS.png

### ISSUE THREAD

**Issue by metallicafan212** [metallicafan212/M212-Editor-Issue-Tracker#20]
Per zone rendering mode

**Comment by OmegaRC59** [comment]
![RM_ZoneS](https://user-images.githubusercontent.com/66154598/88257159-00347f80-cc72-11ea-9970-d0cd1eda5c93.png)
![RM_Zone](https://user-images.githubusercontent.com/66154598/88257162-00cd1600-cc72-11ea-8ee4-3dc4e85b53e6.png)
