### ISSUE TITLE
[IMPROVEMENT] Rewrite line drawing in DX9 to improve speed

### ISSUE THREAD

**Issue by metallicafan212** [metallicafan212/M212-Editor-Issue-Tracker#200]
Current line drawing code is way too slow, and causes massive lag on bigger levels. This is one of the only reasons software is still in the editor, as software draws lines very quickly.

https://docs.microsoft.com/en-us/windows/win32/direct3d9/id3dxline

**Comment by metallicafan212** [comment]
Pushed back, as just implementing that isn't going to fix the issue, it needs a complete rewrite to fix the issues.

**Comment by AdamJD01** [comment]
Closing because DX11 is faster
