### ISSUE TITLE
[BUG] Mesh browser vertex mesh crash

### ISSUE THREAD

**Issue by AdamJD01** [metallicafan212/M212-Editor-Issue-Tracker#206]
![unknown](https://user-images.githubusercontent.com/54454429/142737661-9b577086-a684-44a5-878c-59c7eab7e68d.png)

Adding here just for documentation.

**Comment by metallicafan212** [comment]
Fixed
![image](https://user-images.githubusercontent.com/5996243/142750572-ef5f031d-ee32-4f7e-950f-3406ee631fec.png)
