### ISSUE TITLE
[ICONS] New needed icons

### ISSUE THREAD

**Issue by metallicafan212** [metallicafan212/M212-Editor-Issue-Tracker#211]
on and off icons for
(Top Bar)
~~translation~~
~~rotation~~
~~scale gizmo.~~
(Viewport Bar)
~~show bounds~~
~~show collision~~

~~Master browser~~
~~Prefab browser~~

**Comment by OmegaRC59** [comment]
Rotation
![BN_Giz_Rotate_Off](https://user-images.githubusercontent.com/66154598/146446453-418bd533-7c55-4b03-b085-c9cc745ec86a.png)
![BN_Giz_Rotate_On](https://user-images.githubusercontent.com/66154598/146446456-55bcef8c-43c9-4d04-9944-969ad7c098e6.png)

**Comment by OmegaRC59** [comment]
Icons done
