### ISSUE TITLE
RS_Bounds.png/RS_BoundsS.png

### ISSUE THREAD

**Issue by metallicafan212** [metallicafan212/M212-Editor-Issue-Tracker#22]
Show model/actor bounds

**Comment by OmegaRC59** [comment]
![RS_BoundsS](https://user-images.githubusercontent.com/66154598/88248841-6b248d00-cc57-11ea-8c9a-559b8a69a839.png)
![RS_Bounds](https://user-images.githubusercontent.com/66154598/88248845-6b248d00-cc57-11ea-9517-d7f2e9b2e782.png)
