### ISSUE TITLE
[BUG] Different text colors for properties in the editor

### ISSUE THREAD

**Issue by AdamJD01** [metallicafan212/M212-Editor-Issue-Tracker#220]
Sometimes text is black and on other times it is white.

**Comment by metallicafan212** [comment]
@AdamJD01 Does this happen anymore? I swear it's gone now

**Comment by metallicafan212** [comment]
:)

**Comment by AdamJD01** [comment]
Still happens

![image](https://user-images.githubusercontent.com/54454429/177195723-bf19aefb-0a91-4b5b-8fb7-080f00b5c2d4.png)

![image](https://user-images.githubusercontent.com/54454429/177195747-056795cd-f7bb-43f4-9ca0-1da92cabc46c.png)

**Comment by AdamJD01** [comment]
Fixed
