### ISSUE TITLE
[BUG] Newly imported meshes appear not to LOD

### ISSUE THREAD

**Issue by OmegaRC59** [metallicafan212/M212-Editor-Issue-Tracker#225]
Self explanatory. 

Additionally, you can set the LODBias of an actor below 1 to force it to LOD, with 0 being forced to its maximum LOD. 

Newly imported meshes do not react to LOD through this property, or through distance at all.

**Comment by metallicafan212** [comment]
This is now fixed. Meshes need to be reimported for them to have LODing again, because the information needed wasn't getting generated in the import process.
