### ISSUE TITLE
RS_Event.png/RS_EventS.png

### ISSUE THREAD

**Issue by metallicafan212** [metallicafan212/M212-Editor-Issue-Tracker#24]
Show event lines

**Comment by OmegaRC59** [comment]
![RS_Event](https://user-images.githubusercontent.com/66154598/88243459-4f17f000-cc45-11ea-99cc-ec47969a4401.png)
![RS_EventS](https://user-images.githubusercontent.com/66154598/88243460-4f17f000-cc45-11ea-93e0-be50439d755f.png)

**Comment by OmegaRC59** [comment]
E
