### ISSUE TITLE
RS_Lines.png/RS_LinesS.png

### ISSUE THREAD

**Issue by metallicafan212** [metallicafan212/M212-Editor-Issue-Tracker#26]
Show lines above everything in DX9

**Comment by OmegaRC59** [comment]
![RS_LinesS](https://user-images.githubusercontent.com/66154598/88242009-c1d29c80-cc40-11ea-8ff1-5b5b06c1f1c5.png)
![RS_Lines](https://user-images.githubusercontent.com/66154598/88242010-c1d29c80-cc40-11ea-9797-f98b790a4053.png)
