### ISSUE TITLE
RS_Paths.png/RS_PathsS.png

### ISSUE THREAD

**Issue by metallicafan212** [metallicafan212/M212-Editor-Issue-Tracker#27]
Show path lines

**Comment by OmegaRC59** [comment]
![RS_PathsS](https://user-images.githubusercontent.com/66154598/88242695-cf892180-cc42-11ea-8ff1-8480d7cbdf4e.png)
![RS_Paths](https://user-images.githubusercontent.com/66154598/88242696-cf892180-cc42-11ea-9c8e-df844a3dd9d1.png)
