### ISSUE TITLE
[BUG] A backdrop can follow the camera

### ISSUE THREAD

**Issue by AdamJD01** [metallicafan212/M212-Editor-Issue-Tracker#32]
On some levels when using either DX9 or OpenGL in real time preview a backdrop follows the camera which makes the level hard to see.

**Comment by metallicafan212** [comment]
Did you have Show backdrop on?

Off
![image](https://user-images.githubusercontent.com/5996243/82766098-f0fb9780-9dd0-11ea-948f-758f542798c4.png)

On
![image](https://user-images.githubusercontent.com/5996243/82766105-fd7ff000-9dd0-11ea-8a75-e8ca275cf98c.png)

**Comment by AdamJD01** [comment]
No, I didn't.

**Comment by metallicafan212** [comment]
Oh, in play mode it's designed to do that. That's a engine limitation as it's rendering the backdrop at like Z = 200 before the scene is drawn

**Comment by metallicafan212** [comment]
Closed until further comment.
