### ISSUE TITLE
[BUG] UCC cannot compile HGame and custom packages at the same time

### ISSUE THREAD

**Issue by AdamJD01** [metallicafan212/M212-Editor-Issue-Tracker#39]
When compiling HGame and custom packages you need to use UCC twice. 
UCC only compiles HGame the first time and finishes without compiling the custom packages. 
The custom packages do compile however when using UCC again.

**Comment by metallicafan212** [comment]
Yeah, I've noticed that mine crashes after it compiles HGame.

**Comment by AdamJD01** [comment]
This is now fixed
