### ISSUE TITLE
[BUG] Edit > Select None (Shift Z) does not work

### ISSUE THREAD

**Issue by MaxG-cmd** [metallicafan212/M212-Editor-Issue-Tracker#44]

**Comment by metallicafan212** [comment]
Edit->Select None works fine

Shift -> Z is what doesn't work

**Comment by MaxG-cmd** [comment]
Oh you're right

**Comment by metallicafan212** [comment]
Fixed by implementing another hotkey for it.

Shift + Z selects none now.
