### ISSUE TITLE
[BUG] A duplicate of the hidden properties block in the actor properties and Nothing Selected

### ISSUE THREAD

**Issue by AdamJD01** [metallicafan212/M212-Editor-Issue-Tracker#46]
On times when using the actor properties, the hidden properties block at the bottom displays twice.
The duplicate does disappear when clicking on one of the hidden properties block though.

<img width="471" alt="hiddenactorprops" src="https://user-images.githubusercontent.com/54454429/82917045-c5141980-9f6a-11ea-9602-3a0263f9dd40.png">

**Comment by metallicafan212** [comment]
Does the issue happen if the window is slightly longer? I think it's a drawing bug, but it may be a bug in the way it adds new categories

Anyways, in my UCC, if you don't set a category on a var, then the cat is set to {Hidden} as it's more efficient that way, rather than catching a '' cat.

**Comment by AdamJD01** [comment]
After playing around with this it happens if you make the window smaller and scroll to the bottom.

**Comment by AdamJD01** [comment]
Also I don't want to create a new issue because it is related to the actor properties. 

On times when I select an actor the properties get displayed but at the top it says "Nothing Selected".

**Comment by metallicafan212** [comment]
So the drawing error is a classic UE one, IDK if I can actually fix it (it would take ripping out the code for the backing list and rewriting it).

The name thing is known, but I think it's just not sending the message to change the name for some reason.

**Comment by metallicafan212** [comment]
With the latest version, this seems to not happen.

The extra hidden isn't something I'm going to work on fixing just yet, it's just that the window doesn't redraw right there, and windows doesn't clear a window unless the program tells it to. Basically hall of mirrors.
