### ISSUE TITLE
[BUG] Some textures do not display correctly when using OpenGL

### ISSUE THREAD

**Issue by AdamJD01** [metallicafan212/M212-Editor-Issue-Tracker#48]
When using OpenGL some textures are glitchy in the editor. 

Textures on DX9:
<img width="538" alt="DX9Texture" src="https://user-images.githubusercontent.com/54454429/82917581-829f0c80-9f6b-11ea-9ad5-1ef1b3ee6585.png">

Textures on OpenGL:
<img width="601" alt="OpenGLTexture" src="https://user-images.githubusercontent.com/54454429/82917603-8af74780-9f6b-11ea-9001-1b8f64bcf9b2.png">

**Comment by metallicafan212** [comment]
Honestly, GL is going to get removed once I figure out how to make line thickness adjustments in DX9. Open GL actually has functions to draw lines and set their thickness, but DX9 is drawing them as polygons.

Once that gets added, then GL serves no purpose in the editor anymore and will be removed.
