### ISSUE TITLE
[BUG] Custom actor does not get removed from a level or the actor class window

### ISSUE THREAD

**Issue by AdamJD01** [metallicafan212/M212-Editor-Issue-Tracker#52]
If a custom actor gets deleted from a package then the actor does not get removed from levels and stays in the actor class window despite being deleted and the package recompiled with UCC.

**Comment by metallicafan212** [comment]
Do you mean a .uc file? Because if so, by default it only tracks for files of existing classes if the package already exists. You'll have to delete the .u file and compile again.

**Comment by AdamJD01** [comment]
Sorry should have explained better, yes I meant a .uc file. 

Deleting the package first worked.
