### ISSUE TITLE
Make the editor draw a FOV projection cone out of a CutCameraPos at 90 degrees

### ISSUE THREAD

**Issue by metallicafan212** [metallicafan212/M212-Editor-Issue-Tracker#53]
This will make it easier to frame it from that location, given you know where the target is

**Comment by OmegaRC59** [comment]
UE2's projectors have a square projection preview to show you how to frame the projector, this would likely be better at approximating how a scene is intended to be viewed

**Comment by AdamJD01** [comment]
Implemented by @metallicafan212
