### ISSUE TITLE
Gamestate Dropdown next to the play button

### ISSUE THREAD

**Issue by metallicafan212** [metallicafan212/M212-Editor-Issue-Tracker#54]
This is so the game will always have a correct gamestate and you can specify the exact one you want

**Comment by metallicafan212** [comment]
Pushing back to version 2. Not really important right now.

**Comment by OmegaRC59** [comment]
For future reference, also add a checkbox to enable the log

**Comment by metallicafan212** [comment]
Implemented this into the Top Bar, the level URL now has an option for gamestate (GAMESTATE=) which takes a valid gamestate string and sets it before the level loads.
