### ISSUE TITLE
Surface Properties Sheet

### ISSUE THREAD

**Issue by metallicafan212** [metallicafan212/M212-Editor-Issue-Tracker#57]
Needs to be finished, bugs fixed.

Add in showing of the rotation as well.

**Comment by metallicafan212** [comment]
All the slowness and rendering bugs were fixed by remaking the whole window.

Rotation will be added later, unless I find an easy way to grab/display it.

Layout (for now) will stay the same

**Comment by AdamJD01** [comment]
Cursor does not update when moving mouse off the surface properties sheet.

eg. When resizing the window the double arrowed cursor stays on instead of going back to the default cursor.

**Comment by metallicafan212** [comment]
This is fixed

**Comment by AdamJD01** [comment]
Pressing the hide button does nothing.

**Comment by metallicafan212** [comment]
It should work, are you sure?

It always works for me.

**Comment by AdamJD01** [comment]
The hide button now works with the new build

**Comment by AdamJD01** [comment]
Deleting the Editor ini file seems to have fixed it

**Comment by metallicafan212** [comment]
Ah, ok. That's good then.
