### ISSUE TITLE
[BUG] Massive icon when reopening editor (only happened once)

### ISSUE THREAD

**Issue by AdamJD01** [metallicafan212/M212-Editor-Issue-Tracker#63]
The sphere icon was massive and covered a lot of other icons. 
This went away when closing the editor again though.  

<img width="58" alt="thiccicon" src="https://user-images.githubusercontent.com/54454429/83902828-09ff3380-a755-11ea-80f1-edf84a6f00d9.png">

**Comment by metallicafan212** [comment]
Yeah things like that happen sometimes. I need to recode those controls

**Comment by AdamJD01** [comment]
This happened again but with a different icon. 

<img width="62" alt="bigicon" src="https://user-images.githubusercontent.com/54454429/88614526-d622f900-d087-11ea-9974-92cc661cb8c4.png">

**Comment by metallicafan212** [comment]
I will be replacing these controls with my new fake ones, so this bug should go away when that happens.

**Comment by metallicafan212** [comment]
Since I replaced these controls, I will be closing this issue until new issues are uncovered.

**Comment by AdamJD01** [comment]
Hovering the mouse over these new controls constantly flickers the cursor between the default one and the viewport cursor (only happens on the left side).

**Comment by metallicafan212** [comment]
Fixed. The button bar was setting the cursor when it shouldn't.
