### ISSUE TITLE
[BUG] Selecting Matching Groups and the shortcut (Shift+G) crashes the editor

### ISSUE THREAD

**Issue by AdamJD01** [metallicafan212/M212-Editor-Issue-Tracker#65]
When selecting Edit > Select Surfaces > Matching Groups or using the shortcut (Shift+G) on a level that uses groups the editor crashes with no error and nothing in the log.

**Comment by metallicafan212** [comment]
Interesting.

**Comment by metallicafan212** [comment]
Was a Surface->Actor nullptr issue made by Epic.

Fixed
