### ISSUE TITLE
[BUG] Editor shows no error message when trying to open with a missing package (found by accident)

### ISSUE THREAD

**Issue by AdamJD01** [metallicafan212/M212-Editor-Issue-Tracker#69]
When trying to open the editor it wouldn't open and showed no error message. After a while I had to look in the log to find out what was causing the issue and it turned out I forgot to recompile a package after deleting it lol. 

Adding as a bug because no error message was shown when opening the editor and only found out what the problem was by looking in the log.

**Comment by metallicafan212** [comment]
@AdamJD01 Is this package an editpackage?

**Comment by AdamJD01** [comment]
Yes, it is

**Comment by metallicafan212** [comment]
Changed it to a message box for each missing editpackage.
