### ISSUE TITLE
RD_D9.png\RD_D9S.png

### ISSUE THREAD

**Issue by metallicafan212** [metallicafan212/M212-Editor-Issue-Tracker#7]
DX9 icon
EditorRes\InRes\Viewport\

**Comment by OmegaRC59** [comment]
![RD_D9](https://user-images.githubusercontent.com/66154598/88254598-95cc1100-cc6a-11ea-9ab7-167a4856c5f2.png)
![RD_D9S](https://user-images.githubusercontent.com/66154598/88254599-9664a780-cc6a-11ea-89a1-165f7a56ce4e.png)


rad
