### ISSUE TITLE
RS_OSAct\RS_OSActS

### ISSUE THREAD

**Issue by metallicafan212** [metallicafan212/M212-Editor-Issue-Tracker#81]
Out of bounds actor rendering.

Currently a temp icon.

**Comment by OmegaRC59** [comment]
![RS_OSActS](https://user-images.githubusercontent.com/66154598/88244574-111ccb00-cc49-11ea-8237-b6534d091e21.png)
![RS_OSAct](https://user-images.githubusercontent.com/66154598/88244575-11b56180-cc49-11ea-8342-3e8bc5ed4791.png)
