### ISSUE TITLE
[BUG] Cannot import .t3d files

### ISSUE THREAD

**Issue by AdamJD01** [metallicafan212/M212-Editor-Issue-Tracker#82]
When exporting a map as a .t3d file and importing the file as a new map or part of an existing map the editor crashes with this error. 

<img width="307" alt="ImportError" src="https://user-images.githubusercontent.com/54454429/86503193-911ae800-bda3-11ea-86ac-6bb423bf151a.png">

**Comment by metallicafan212** [comment]
Fixed this error, editor was exporting ObjectInteral array when it shouldn't.

Temp fix was to just ignore these properties, as it should NEVER use the saved ones; they should all be dynamic.
