### ISSUE TITLE
[BUG] Color picker forgets last location

### ISSUE THREAD

**Issue by MaxG-cmd** [metallicafan212/M212-Editor-Issue-Tracker#83]
When changing the color of a particle and selecting the color picker, it does not start out at the actual base color. Instead, it always starts at R=180, G=221, B=64 (which I believe is the default). The intended behavior is for the color picker to start at the color that is actually in the property box.

![image](https://user-images.githubusercontent.com/56568996/86968489-dfc4db00-c131-11ea-8695-dc4a510392cf.png)

**Comment by metallicafan212** [comment]
I haven't even changed that code, so it was probably broken in the proto as
well.

**Comment by MaxG-cmd** [comment]
> I haven't even changed that code, so it was probably broken in the proto as well.

It definitely was not broken in some recent versions. I clearly remember being able to go in and just slightly change it without having to guess the last position. No idea what happened.

**Comment by metallicafan212** [comment]
Fixed.
