### ISSUE TITLE
[BUG] Forgetting to save a prefab package crashes the editor

### ISSUE THREAD

**Issue by AdamJD01** [metallicafan212/M212-Editor-Issue-Tracker#84]
Adding a prefab to a map and closing the editor without saving the prefab package causes this error. 

<img width="300" alt="Untitled" src="https://user-images.githubusercontent.com/54454429/87225921-5eb35100-c388-11ea-969b-f850d884710d.png">

**Comment by metallicafan212** [comment]
Should be fixed now
