### ISSUE TITLE
Particle Selection Box Can Be Too Large

### ISSUE THREAD

**Issue by MaxG-cmd** [metallicafan212/M212-Editor-Issue-Tracker#89]
It becomes impossible to select actors obscured by large particle systems without switching to software render, since the only thing you can select are the particles. Perhaps hide the system and only show the icon when not in play?

**Comment by MaxG-cmd** [comment]
Oh also, and this happens in other renderers, too, but if fly through a particle system while not in play mode, they become all sorts of random colors.

**Comment by metallicafan212** [comment]
Not much I can do on this front, but I can look further. I may have to have a check in render.dll to not render them when GIsEditor and !Realtime.

**Comment by metallicafan212** [comment]
Particles do not render in non-realtime mode now.
