### ISSUE TITLE
RD_Soft.png/RD_SoftS.png

### ISSUE THREAD

**Issue by metallicafan212** [metallicafan212/M212-Editor-Issue-Tracker#9]
Software icon

**Comment by OmegaRC59** [comment]
![RD_SoftS](https://user-images.githubusercontent.com/66154598/88253907-543a6680-cc68-11ea-9958-7a3d0f8dc2a9.png)
![RD_Soft](https://user-images.githubusercontent.com/66154598/88253908-54d2fd00-cc68-11ea-9cb0-5c96d548ebae.png)
