### ISSUE TITLE
Toolbar: Edit Default Properties

### ISSUE THREAD

**Issue by metallicafan212** [metallicafan212/M212-Editor-Issue-Tracker#97]

**Comment by OmegaRC59** [comment]
![TB_Pre_Add](https://user-images.githubusercontent.com/66154598/90305342-6c239580-de76-11ea-9a26-6f2a8a77d426.png)

**Comment by OmegaRC59** [comment]
![TB_Props](https://user-images.githubusercontent.com/66154598/90305367-be64b680-de76-11ea-93cf-ad6722723058.png)

**Comment by OmegaRC59** [comment]
posted the wrong icon, fixed
