### ISSUE TITLE
Toolbar: Next Group and Previous Group

### ISSUE THREAD

**Issue by metallicafan212** [metallicafan212/M212-Editor-Issue-Tracker#99]

**Comment by OmegaRC59** [comment]
![BN_Redo](https://user-images.githubusercontent.com/66154598/88260433-35909b80-cc79-11ea-8282-5ba2ed21bc15.png)
![BN_Undo](https://user-images.githubusercontent.com/66154598/88260434-35909b80-cc79-11ea-8f38-274bdc31b439.png)

**Comment by metallicafan212** [comment]
Using existing
